openapi: 3.0.3
info:
  title: STD23014 - TD1
  version: '1.0.1'
servers:
  - url: https://localhost.std23014.com
paths:
  /customers:
    get:
      responses:
        200:
          description: customers list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
components:
  schemas:
    Customer:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
