openapi: 3.0.3
info:
  title: STD23014 - TD5
  version: '1.0.3'
servers:
  - url: https://localhost.STD23014.com
paths:
  /customers:
    put:
      summary: Update a Customer info
      description: replace customer
      requestBody:
        description: new customer information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        200:
          description: updated customer information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
    patch:
      summary: update a Customer
      description: Modify a Customer info.
      requestBody:
        description: Customer modified information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartialCustomer'
        required: true
      responses:
        200:
          description: updated customer object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer
      required:
        - id
        - name
        - age
    PartialCustomer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer
      required:
        - id
